---
name: Reusable workflow for spellcheck with codespell

on:
  workflow_call:
    inputs:
      ignore_words_list:
        description: 'Comma-separated list of words which will be ignored by codespell.'
        type: string
        required: false
        default: ''
      skip:
        description: 'Comma-separated list of files to skip (it accepts globs as well).'
        type: string
        required: false
        default: './.git'

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Codespell
      uses: codespell-project/actions-codespell@v1
      with:
        check_filenames: true
        ignore_words_list: "${{ inputs.ignore_words_list }}"
        skip: "${{ inputs.skip }}"
