---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "dev-sec/.github/.github/workflows/codespell.yml@main"
    with:
      ignore_words_list: "commitish"
